apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: vrp-deployment-config
spec:
  #number of replicas generated
  replicas: 1
  #assigns labels to the pods for future selection
  selector:
      app: vrp-sql

  template:
    metadata:
      labels:
        app: vrp-sql

    spec:
      containers:
        - name: vrp-sql-container
          image: >-
            docker-registry.default.svc:5000/test/test:latest
